import { create } from 'zustand'
import type { Task, CreateTaskRequest, UpdateTaskRequest } from '../types'
import { api, repeatApi } from '../api'
import { useUIStore } from './uiStore'

/**
 * 根据全局默认提醒偏移量（uiStore.defaultReminderOffset）自动填充 reminder。
 *
 * 规则：
 * - offset > 0 且任务有 due_date 且未显式设置 reminder 时，
 *   reminder = due_date - offset 分钟。
 * - offset 为 0（关闭自动提醒）、无 due_date 或已有 reminder 时，原样返回。
 *
 * @param task 待处理的任务数据（Partial<Task> 或 CreateTaskRequest）
 * @returns 处理后的任务数据
 */
export function applyDefaultReminder<T extends { due_date?: string; reminder?: string | null }>(task: T): T {
  const offset = useUIStore.getState().defaultReminderOffset
  if (offset > 0 && task.due_date && !task.reminder) {
    const due = new Date(task.due_date)
    due.setMinutes(due.getMinutes() - offset)
    return { ...task, reminder: due.toISOString() }
  }
  return task
}

/**
 * 判断给定 reminder 是否等于 due_date - offset（即由默认提醒规则自动生成）。
 *
 * 用于 updateTask 场景：当用户修改 due_date 时，若原 reminder 恰好是自动生成的，
 * 则同步更新 reminder；若用户曾手动设置过 reminder（与自动计算值不符），则不覆盖。
 */
function isAutoGeneratedReminder(reminder: string, dueDate: string, offset: number): boolean {
  if (offset <= 0) return false
  const expected = new Date(new Date(dueDate).getTime() - offset * 60000).toISOString()
  return reminder === expected
}

interface TaskState {
  tasks: Task[]
  loading: boolean
  setTasks: (tasks: Task[]) => void
  loadTasks: () => Promise<void>
  createTask: (req: CreateTaskRequest) => Promise<Task | null>
  updateTask: (id: number, updates: UpdateTaskRequest) => Promise<boolean>
  deleteTask: (id: number) => Promise<boolean>
  duplicateTask: (id: number) => Promise<Task | null>
  togglePin: (id: number) => Promise<boolean>
  toggleTask: (task: Task) => Promise<{ success: boolean; newTaskGenerated: boolean }>
  reorderTasks: (items: { id: number; sort_order: number }[]) => Promise<boolean>
  moveTask: (taskId: number, newDate: string) => Promise<boolean>
  reloadAll: () => Promise<void>
}

export const useTaskStore = create<TaskState>((set, get) => ({
  tasks: [],
  loading: true,

  setTasks: (tasks) => set({ tasks }),

  loadTasks: async () => {
    set({ loading: true })
    try {
      const data = await api.getTasks()
      set({ tasks: data, loading: false })
    } catch (error) {
      console.error('Failed to load tasks:', error)
      set({ loading: false })
    }
  },

  createTask: async (req) => {
    try {
      // 根据全局默认提醒偏移自动填充 reminder（若未显式设置）
      const enrichedReq = applyDefaultReminder(req)
      const newTask = await api.createTask(enrichedReq)
      set((state) => ({ tasks: [newTask, ...state.tasks] }))
      return newTask
    } catch (error) {
      console.error('Failed to create task:', error)
      return null
    }
  },

  updateTask: async (id, updates) => {
    try {
      // 若更新了 due_date 但未显式更新 reminder，检查原 reminder 是否由默认规则自动生成；
      // 若是则同步更新 reminder，保持"截止前 N 分钟"的偏移；否则保留用户手动设置的值。
      if (updates.due_date && !('reminder' in updates)) {
        const current = get().tasks.find((t) => t.id === id)
        if (current?.reminder && current.due_date) {
          const offset = useUIStore.getState().defaultReminderOffset
          if (offset > 0 && isAutoGeneratedReminder(current.reminder, current.due_date, offset)) {
            const newReminder = new Date(new Date(updates.due_date).getTime() - offset * 60000).toISOString()
            updates = { ...updates, reminder: newReminder }
          }
        }
      }
      await api.updateTask(id, updates)
      set((state) => ({
        tasks: state.tasks.map((t) => {
          // 更新顶层任务本身
          if (t.id === id) {
            return { ...t, ...updates, updated_at: new Date().toISOString() }
          }
          // 同时检查并更新嵌套的子任务
          if (t.subtasks && t.subtasks.some((st) => st.id === id)) {
            return {
              ...t,
              subtasks: t.subtasks.map((st) =>
                st.id === id ? { ...st, ...updates, updated_at: new Date().toISOString() } : st,
              ),
            }
          }
          return t
        }),
      }))
      return true
    } catch (error) {
      console.error('Failed to update task:', error)
      return false
    }
  },

  deleteTask: async (id) => {
    try {
      await api.deleteTask(id)
      set((state) => ({
        tasks: state.tasks
          .filter((t) => t.id !== id)
          .map((t) => (t.subtasks ? { ...t, subtasks: t.subtasks.filter((st) => st.id !== id) } : t)),
      }))
      return true
    } catch (error) {
      console.error('Failed to delete task:', error)
      return false
    }
  },

  duplicateTask: async (id) => {
    try {
      const newTask = await api.duplicateTask(id)
      set((state) => ({ tasks: [newTask, ...state.tasks] }))
      return newTask
    } catch (error) {
      console.error('Failed to duplicate task:', error)
      return null
    }
  },

  togglePin: async (id) => {
    try {
      const task = get().tasks.find((t) => t.id === id)
      if (!task) return false
      const newPinned = !task.pinned
      await api.updateTask(id, { pinned: newPinned })
      set((state) => ({
        tasks: state.tasks.map((t) =>
          t.id === id ? { ...t, pinned: newPinned, updated_at: new Date().toISOString() } : t,
        ),
      }))
      return true
    } catch (error) {
      console.error('Failed to toggle pin:', error)
      return false
    }
  },

  toggleTask: async (task) => {
    try {
      if (!task.completed && task.repeat_rule) {
        // 新 RRULE 格式（FREQ=...）使用 complete_recurring_task 命令；
        // 旧格式（JSON/字符串）仍走 complete_task 命令。
        const isRRule = task.repeat_rule.trim().startsWith('FREQ=')
        const newTaskId = isRRule
          ? await repeatApi.completeRecurringTask(task.id)
          : ((await api.completeTask(task.id)).new_task_id ?? 0)

        set((state) => ({
          tasks: state.tasks.map((t) =>
            t.id === task.id ? { ...t, completed: true, updated_at: new Date().toISOString() } : t,
          ),
        }))
        if (newTaskId) {
          await get().loadTasks()
          return { success: true, newTaskGenerated: true }
        }
        return { success: true, newTaskGenerated: false }
      }
      await api.updateTask(task.id, { completed: !task.completed })
      set((state) => ({
        tasks: state.tasks.map((t) => (t.id === task.id ? { ...t, completed: !task.completed } : t)),
      }))
      return { success: true, newTaskGenerated: false }
    } catch (error) {
      console.error('Failed to toggle task:', error)
      return { success: false, newTaskGenerated: false }
    }
  },

  reorderTasks: async (items) => {
    try {
      await api.reorderTasks(items)
      const sortOrderMap = new Map(items.map((item) => [item.id, item.sort_order]))
      set((state) => ({
        tasks: state.tasks.map((t) => (sortOrderMap.has(t.id) ? { ...t, sort_order: sortOrderMap.get(t.id)! } : t)),
      }))
      return true
    } catch (error) {
      console.error('Failed to reorder tasks:', error)
      await get().loadTasks()
      return false
    }
  },

  moveTask: async (taskId, newDate) => {
    try {
      const task = get().tasks.find((t) => t.id === taskId)
      const updates: UpdateTaskRequest = { due_date: newDate }
      if (task?.end_date && task?.due_date) {
        const duration = new Date(task.end_date).getTime() - new Date(task.due_date).getTime()
        updates.end_date = new Date(new Date(newDate).getTime() + duration).toISOString()
      }
      await api.updateTask(taskId, updates)
      set((state) => ({
        tasks: state.tasks.map((t) =>
          t.id === taskId ? { ...t, ...updates, updated_at: new Date().toISOString() } : t,
        ),
      }))
      return true
    } catch (error) {
      console.error('Failed to move task:', error)
      return false
    }
  },

  reloadAll: async () => {
    await get().loadTasks()
  },
}))
